"""Generate a concise repository map for Codex handoffs.

The script reads repository paths and writes only docs/repo_map.md. It skips
cache/build directories, generated reports, and large artifacts by default.
"""

from __future__ import annotations

import os
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "docs" / "repo_map.md"
MAX_FILE_BYTES = 512 * 1024

SKIP_DIR_NAMES = {
    ".cache",
    ".git",
    ".mypy_cache",
    ".nox",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "cache",
    "dist",
    "env",
    "node_modules",
    "venv",
}
GENERATED_TOP_LEVEL_DIRS = {"reports"}

MAJOR_DIRS = [
    (".agents/skills", "Project-specific Codex Skills and workflow gates."),
    (".github", "Repository automation such as CI workflows."),
    ("docs", "Project process notes, readiness gates, designs, logs, and maps."),
    ("scripts", "Workflow tooling; scripts here must not fetch data or trade."),
    ("src/features", "Factor calculations, validation, normalization, combination, and diagnostics."),
    ("src/backtest", "Simulated long-only backtester and metrics helpers."),
    ("src/data", "Strict local CSV loaders and metadata review helpers."),
    (
        "src/reporting",
        "Experiment log and registry helpers; plotting helpers are placeholder-only future work.",
    ),
    ("research", "Synthetic and committed-fixture demo workflows."),
    ("tests", "Deterministic tests for research logic and guardrails."),
    ("tests/fixtures", "Tiny committed synthetic fixtures only."),
    ("lean", "LEAN-adjacent planning/scaffold files under no-trading guardrails."),
    ("reports", "Generated synthetic reports and logs; summarized but not traversed."),
]

IMPORTANT_FILES = [
    ("AGENTS.md", "Agent guardrails, command-output controls, and repo safety rules."),
    ("docs/current_handoff.md", "Shortest current-state handoff; read this first."),
    ("docs/repo_map.md", "Generated concise repo map."),
    ("docs/codex_long_running_controller.md", "Continuation and stop-condition controller."),
    (".agents/skills/staged-quant-workflow/SKILL.md", "Reusable staged workflow Skill."),
    ("PROJECT_SPEC.md", "Research scope, assumptions, non-goals, and leakage rules."),
    ("README.md", "Newcomer overview and runnable demo guidance."),
    ("CHANGELOG.md", "User-visible repository changes."),
    ("docs/engineering_log.md", "Chronological engineering notes and validation history."),
    ("docs/decision_log.md", "Durable research and workflow decisions."),
    ("docs/troubleshooting_log.md", "Failures, recovery steps, and prevention notes."),
    ("EXPERIMENT_LOG.md", "Research experiment records; not for workflow-only changes."),
    ("pyproject.toml", "Package metadata and test dependencies."),
]

TEST_COMMANDS = [
    ("Full tests", "python -m pytest -q"),
    ("Lint repository", "python -m ruff check ."),
    ("Compile source, tests, and research", "python -m compileall src tests research"),
    ("Compile LEAN scaffold", "python -m compileall lean"),
    ("Build distribution", "python -m build"),
    ("Repo map refresh", "python scripts/repo_map.py"),
    ("Branch whitespace check", "git diff --check origin/main..HEAD"),
    ("Skill audit for workflow/Skill changes", ".\\scripts\\audit-skills.ps1"),
]


def _is_skipped_dir(name: str) -> bool:
    lowered = name.lower()
    return (
        lowered in SKIP_DIR_NAMES
        or "pycache" in lowered
        or lowered.endswith(".egg-info")
    )


def _is_generated_dir(rel_path: Path) -> bool:
    return bool(rel_path.parts) and rel_path.parts[0] in GENERATED_TOP_LEVEL_DIRS


def _iter_mapped_files() -> list[Path]:
    mapped: list[Path] = []
    for root, dirs, files in os.walk(REPO_ROOT):
        root_path = Path(root)
        rel_root = root_path.relative_to(REPO_ROOT)

        dirs[:] = sorted(
            dirname
            for dirname in dirs
            if not _is_skipped_dir(dirname)
            and not _is_generated_dir(rel_root / dirname)
        )

        if _is_generated_dir(rel_root):
            dirs[:] = []
            continue

        for filename in sorted(files):
            path = root_path / filename
            rel_path = path.relative_to(REPO_ROOT)
            try:
                if path.stat().st_size > MAX_FILE_BYTES:
                    continue
            except OSError:
                continue
            mapped.append(rel_path)
    return mapped


def _count_under(files: list[Path], rel_dir: str) -> int:
    prefix = Path(rel_dir).parts
    if rel_dir == "reports":
        return 0
    return sum(1 for path in files if path.parts[: len(prefix)] == prefix)


def _count_label(count: int) -> str:
    suffix = "file" if count == 1 else "files"
    return f"{count} mapped {suffix}"


def _exists_label(rel_path: str) -> str:
    if REPO_ROOT / rel_path == OUTPUT_PATH:
        return "generated by this script"
    path = REPO_ROOT / rel_path
    if path.exists():
        return "present"
    return "missing"


def build_repo_map() -> str:
    files = _iter_mapped_files()
    lines = [
        "# Repo Map",
        "",
        "Generated by `python scripts/repo_map.py`.",
        "",
        "Scope: concise orientation for Codex handoffs. Cache/build directories, generated reports, and files larger than 512 KiB are skipped by default.",
        "",
        "## Major Directories",
        "",
        "| Path | Purpose | Map status |",
        "| --- | --- | --- |",
    ]

    for rel_dir, purpose in MAJOR_DIRS:
        path = REPO_ROOT / rel_dir
        if rel_dir == "reports":
            status = "generated outputs summarized only"
        elif path.exists():
            status = _count_label(_count_under(files, rel_dir))
        else:
            status = "missing"
        lines.append(f"| `{rel_dir}/` | {purpose} | {status} |")

    lines.extend(
        [
            "",
            "## Important Files",
            "",
        ]
    )
    for rel_path, purpose in IMPORTANT_FILES:
        lines.append(f"- `{rel_path}` ({_exists_label(rel_path)}): {purpose}")

    lines.extend(
        [
            "",
            "## Test And Validation Commands",
            "",
        ]
    )
    for label, command in TEST_COMMANDS:
        lines.append(f"- {label}: `{command}`")

    lines.extend(
        [
            "",
            "## Output Discipline",
            "",
            "- Read `docs/current_handoff.md` before deeper logs.",
            "- Do not print full generated reports or large logs by default; inspect targeted ranges only when needed.",
            "- Use capped command output for unknown commands, and save full output to a temp file when full review is necessary.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(build_repo_map(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
